[package]
name = "async-lsp"
version = "0.0.4"
edition = "2021"
description = "Asynchronous Language Server Protocol (LSP) framework based on tower"
keywords = ["lsp", "language-server", "tower"]
categories = ["asynchronous"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/oxalica/async-lsp"
exclude = ["/generate_omni_trait.sh"]

# Required features:
# - std::future::poll_fn
# - std::task::ready!
rust-version = "1.64" # Sync with CI!

[features]
default = ["client-monitor", "omni-trait", "stdio", "tracing"]
client-monitor = ["rustix/event", "rustix/process", "windows-sys"]
omni-trait = []
stdio = ["rustix/fs", "tokio/net"]
tracing = ["dep:tracing"]

[[example]]
name = "client_builder"
required-features = ["omni-trait", "tracing"]

[[example]]
name = "client_trait"
required-features = ["omni-trait", "tracing"]

[[example]]
name = "server_builder"
required-features = ["client-monitor", "omni-trait", "stdio", "tracing"]

[[example]]
name = "server_trait"
required-features = ["client-monitor", "omni-trait", "stdio", "tracing"]

[[test]]
name = "unit_test"
required-features = ["omni-trait"]

[[test]]
name = "stdio"
harness = false
required-features = ["stdio"]

[dependencies]
either = "1.8.1"
futures = { version = "0.3.28", default-features = false, features = ["async-await", "std"] }
lsp-types = "0.94.0"
pin-project-lite = "0.2.9"
rustix = { version = "0.38", optional = true }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["io-util", "rt", "sync"] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
tracing = { version = "0.1.37", optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.48.0", features = ["Win32_Foundation", "Win32_System_Threading"], optional = true }

[dev-dependencies]
async-io = "1.13.0"
tokio = { version = "1.27.0", features = ["io-std", "io-util", "macros", "process", "rt", "time"] }
tower = "0.4.13"
tracing-subscriber = "0.3.16"
