[package]
name = "async-lsp"
version = "0.0.1"
edition = "2021"
description = "WIP: Asynchronous Language Server Protocol framework"
keywords = ["lsp", "language-server", "tower"]
categories = ["asynchronous"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/oxalica/async-lsp"

[features]
default = ["stdio"]
stdio = ["tokio/net"]

[dependencies]
either = "1.8.1"
futures = { version = "0.3.28", default-features = false, features = ["async-await", "std"] }
lsp-types = "0.94.0"
pin-project-lite = "0.2.9"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["io-util", "rt", "sync"] }
tower-layer = "0.3.2"
tower-service = "0.3.2"

[target.'cfg(target_os = "linux")'.dependencies]
async-pidfd = { version = "0.1.4", default-features = false }
libc = "0.2.141"
tokio = { version = "1.27.0", features = ["net"] }

[dev-dependencies]
tokio = { version = "1.27.0", features = ["io-std", "io-util", "macros", "rt", "time"] }
tower = "0.4.13"
