name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '29 1 * * *' # *-*-* 01:29:00 UTC

permissions:
  contents: read

env:
  RUST_BACKTRACE: full
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable, "1.64"] # Sync with Cargo.toml.
        os: [ubuntu-latest, macos-latest]
    name: Test ${{matrix.rust}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --workspace --all-targets

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy --workspace --all-targets -- -Dclippy::all

  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/install@cargo-outdated
      - run: cargo outdated --workspace --exit-code 1
